server:
  use-forward-headers: true
  port: 8080

management:
  port: 7979
  context-path: /management
  security:
    enabled: false

zuul:
  routes:
    app:
      path: /app/**
      url: http://ui.default.svc.cluster.local

spring:
  boot:
    admin:
      url: http://boot-admin.default.svc.cluster.local
      client:
        prefer-ip: true
        enabled: true
